### ISSUE TITLE
Switching appointments with arrow keys past last appointment causes crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bradrydzewski/gwt-cal#11]
```
What steps will reproduce the problem?
1.Select last appointment using arrow keys
2.Use the arrow keys to select the "next" appointment

What is the expected output? What do you see instead?
The cursor should stay selecting the current appointment. The cursor does
stay selecting the last appointment, but the arrow key functionality stops
working correctly because of the crash.

What version of the product are you using? On what operating system?
gwt-cal 8.2
gwt 1.7
windows xp

Please provide any additional information below.
[ERROR] Uncaught exception escaped
java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at
com.bradrydzewski.gwt.calendar.client.CalendarView.selectNextAppointment(Calenda
rView.java:145)
    at
com.bradrydzewski.gwt.calendar.client.DayView.keyboardNavigation(DayView.java:32
8)
    at com.bradrydzewski.gwt.calendar.client.DayView$3.onKeyDown(DayView.java:113)
    at com.google.gwt.event.dom.client.KeyDownEvent.dispatch(KeyDownEvent.java:54)
    at com.google.gwt.event.dom.client.KeyDownEvent.dispatch(KeyDownEvent.java:1)
    at
com.google.gwt.event.shared.HandlerManager$HandlerRegistry.fireEvent(HandlerMana
ger.java:65)
    at
com.google.gwt.event.shared.HandlerManager$HandlerRegistry.access$1(HandlerManag
er.java:53)
    at
com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:178)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:52)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:116)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:90)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1320)
    at com.google.gwt.user.client.DOM.dispatchEventAndCatch(DOM.java:1299)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1262)
    at sun.reflect.GeneratedMethodAccessor348.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at
com.google.gwt.dev.shell.ie.IDispatchImpl.callMethod(IDispatchImpl.java:126)
    at com.google.gwt.dev.shell.ie.IDispatchProxy.invoke(IDispatchProxy.java:155)
    at com.google.gwt.dev.shell.ie.IDispatchImpl.Invoke(IDispatchImpl.java:294)
    at com.google.gwt.dev.shell.ie.IDispatchImpl.method6(IDispatchImpl.java:194)
    at org.eclipse.swt.internal.ole.win32.COMObject.callback6(COMObject.java:117)
    at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
    at
org.eclipse.swt.internal.ole.win32.IOleInPlaceActiveObject.TranslateAccelerator(
IOleInPlaceActiveObject.java:22)
    at
org.eclipse.swt.ole.win32.OleFrame.translateOleAccelerator(OleFrame.java:734)
    at org.eclipse.swt.ole.win32.OleFrame.getMsgProc(OleFrame.java:210)
    at org.eclipse.swt.internal.win32.OS.PeekMessageW(Native Method)
    at org.eclipse.swt.internal.win32.OS.PeekMessage(OS.java:2389)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:2963)
    at
com.google.gwt.dev.SwtHostedModeBase.processEvents(SwtHostedModeBase.java:235)
    at com.google.gwt.dev.HostedModeBase.pumpEventLoop(HostedModeBase.java:558)
    at com.google.gwt.dev.HostedModeBase.run(HostedModeBase.java:405)
    at com.google.gwt.dev.HostedMode.main(HostedMode.java:232)
```

Original issue reported on code.google.com by `SpaceRoo...@gmail.com` on 13 Aug 2009 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
I listed my gwt-cal version as 8.2. I meant 0.8.2.
```

Original comment by `SpaceRoo...@gmail.com` on 13 Aug 2009 at 6:23

**Comment by GoogleCodeExporter** [comment]
```
This is fixed in the 0.9 release, and includes unit tests
```

Original comment by `Brad.Ryd...@gmail.com` on 29 Oct 2009 at 3:57
- Changed state: **Started**
- Added labels: **Release0.9**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `Brad.Ryd...@gmail.com` on 17 Dec 2009 at 5:01
- Changed state: **Fixed**
