### ISSUE TITLE
MonthView drag drop Null Pointer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bradrydzewski/gwt-cal#50]
```
When you drag/drop appointments on the MonthView the hosted mode runtime throws 
a null pointer. Visually there is 
no impact, everything works fine on the surface, but I see the following error 
pasted below -

(Note: I never noticed this error in the past. Not sure when/how it was 
introduced or if it always existed ever 
since we added drag/drop functionality)

01:48:03.878 [ERROR] [gwt_cal_demo] Uncaught exception escaped
java.lang.NullPointerException: null
    at com.allen_sauer.gwt.dnd.client.PickupDragController.dragMove(PickupDragController.java:186)
    at com.allen_sauer.gwt.dnd.client.MouseDragHandler.actualMove(MouseDragHandler.java:127)
    at com.allen_sauer.gwt.dnd.client.DeferredMoveCommand.execute(DeferredMoveCommand.java:48)
    at com.allen_sauer.gwt.dnd.client.DeferredMoveCommand.scheduleOrExecute(DeferredMoveCommand.java:82)
    at com.allen_sauer.gwt.dnd.client.MouseDragHandler.onMouseMove(MouseDragHandler.java:295)
    at com.google.gwt.event.dom.client.MouseMoveEvent.dispatch(MouseMoveEvent.java:54)
    at com.google.gwt.event.dom.client.MouseMoveEvent.dispatch(MouseMoveEvent.java:1)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.fireEvent(HandlerManager.java:65)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.access$1(HandlerManager.java:53)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:178)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:52)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:116)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:100)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1307)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1263)
    at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessagesWhileWaitingForReturn(BrowserChannel.java:1713)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:165)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:264)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:188)
    at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessagesWhileWaitingForReturn(BrowserChannel.java:1713)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:165)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeBoolean(ModuleSpace.java:179)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeBoolean(JavaScriptHost.java:35)
    at com.google.gwt.user.client.Window.confirm(Window.java)
    at com.bradrydzewski.gwt.calendar.demo.client.GoogleCalendarPanel$9.onUpdate(GoogleCalendarPanel.java:177)
    at com.bradrydzewski.gwt.calendar.client.event.UpdateEvent.dispatch(UpdateEvent.java:105)
    at com.bradrydzewski.gwt.calendar.client.event.UpdateEvent.dispatch(UpdateEvent.java:1)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.fireEvent(HandlerManager.java:65)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.access$1(HandlerManager.java:53)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:178)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:52)
    at com.bradrydzewski.gwt.calendar.client.event.UpdateEvent.fire(UpdateEvent.java:56)
    at com.bradrydzewski.gwt.calendar.client.CalendarWidget.fireUpdateEvent(CalendarWidget.java:458)
    at com.bradrydzewski.gwt.calendar.client.monthview.MonthView$2.onDragEnd(MonthView.java:185)
    at com.allen_sauer.gwt.dnd.client.DragHandlerCollection.fireDragEnd(DragHandlerCollection.java:37)
    at com.allen_sauer.gwt.dnd.client.AbstractDragController.dragEnd(AbstractDragController.java:138)
    at com.allen_sauer.gwt.dnd.client.PickupDragController.dragEnd(PickupDragController.java:170)
    at com.allen_sauer.gwt.dnd.client.MouseDragHandler.drop(MouseDragHandler.java:155)
    at com.allen_sauer.gwt.dnd.client.MouseDragHandler.onMouseUp(MouseDragHandler.java:347)
    at com.google.gwt.event.dom.client.MouseUpEvent.dispatch(MouseUpEvent.java:54)
    at com.google.gwt.event.dom.client.MouseUpEvent.dispatch(MouseUpEvent.java:1)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.fireEvent(HandlerManager.java:65)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.access$1(HandlerManager.java:53)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:178)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:52)
    at com.google.gwt.event.dom.client.DomEvent.fireNativeEvent(DomEvent.java:116)
    at com.google.gwt.user.client.ui.Widget.onBrowserEvent(Widget.java:100)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1307)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1263)
    at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessagesWhileWaitingForReturn(BrowserChannel.java:1713)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:165)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:264)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:188)
    at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessages(BrowserChannel.java:1668)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:401)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)
    at java.lang.Thread.run(Thread.java:636)

```

Original issue reported on code.google.com by `Brad.Ryd...@gmail.com` on 21 Apr 2010 at 8:50

**Comment by GoogleCodeExporter** [comment]
Original comment by `Brad.Ryd...@gmail.com` on 12 May 2010 at 7:08
- Changed state: **Fixed**
- Added labels: **Release0.9**
