### ISSUE TITLE
Month view is not displaying the appointment.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bradrydzewski/gwt-cal#70]
```
What steps will reproduce the problem?
1. Please create an appointment with start date 06/26/2010 00:00:00  and end 
date 06/27/2010 00:00:00 dates are in (MM/dd/yyyy hh:mm:ss) format.

What is the expected output? What do you see instead?
getting error message:
17:17:45.569 [ERROR] Uncaught exception escaped
com.google.gwt.core.client.JavaScriptException: (Error): Invalid argument.
 number: -2147024809
 description: Invalid argument.
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:195)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:264)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessages(BrowserChannel.java:1668)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:401)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)
    at java.lang.Thread.run(Thread.java:619)

What version of the product are you using? On what operating system?
0.9.1

Please provide any additional information below.

created an appointment and added it to calendar, displaying in month view

=============================
Appointment appt = new Appointment();                       
DateTimeFormat calformat = DateTimeFormat.getFormat("yyyy-MM-dd hh:mm:ss");
appt.setStart(calformat.parse("2010-06-26 00:00:00"));
appt.setEnd(calformat.parse("2010-06-27 00:00:00"));
appt.setTitle("test1");
appt.setDescription("TEST");
appt.setStyle(GOOGLE_STYLES[Random.nextInt(GOOGLE_STYLES.length)]);
appt.setLocation("Minneapolis");
calendar.add(appt);
==============================

Month view is giving error message, not displaying the appointment in calendar. 
It is displaying the appointment in day view and week view correctly.

```

Original issue reported on code.google.com by `murali...@gmail.com` on 19 Jul 2010 at 10:35

**Comment by GoogleCodeExporter** [comment]
```
operating system is Windows XP.
```

Original comment by `murali...@gmail.com` on 19 Jul 2010 at 10:39

**Comment by GoogleCodeExporter** [comment]
```
yes, I have gotten this error in the past. This happens when the MonthView 
tries to calculate the size of its cells, but the Widget is not yet completely 
rendered in your Browser. As a result, the size comes back as a negative 
number, causing a crash.

In the DayView, we solve this in line 192 where we check to make sure the 
height is > 0.

I'll need to add similar logic to the MonthView .... I'll need to run some 
tests, but this shouldn't be too bad ....
```

Original comment by `Brad.Ryd...@gmail.com` on 20 Jul 2010 at 12:11
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
when are you planing to fix this issue ?
```

Original comment by `MaryKise...@gmail.com` on 22 Aug 2010 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
Using DeferredCommand can solve this problem temporarily.

        DeferredCommand.addCommand(
                new Command() {
                    public void execute() {
                        calendar.resumeLayout();
                    }
                }
        );
```

Original comment by `yy.yo...@gmail.com` on 10 Oct 2010 at 11:13
