### ISSUE TITLE
scroll bar for all day appointments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bradrydzewski/gwt-cal#73]
```
Description of the new feature:
Would it be possible add a scroll bar for all day appointments?

If there are more appointments in day view or week view they are taking entire 
screen.. and throwing error message. I am attching the screenshot of day view. 
-----------------------------------
error message:
16:16:31.272 [ERROR] [ncms] Uncaught exception escaped
java.lang.AssertionError: CSS heights should not be negative
    at com.google.gwt.user.client.ui.UIObject.setHeight(UIObject.java:607)
    at com.bradrydzewski.gwt.calendar.client.dayview.DayView.doSizing(DayView.java:193)
    at com.bradrydzewski.gwt.calendar.client.CalendarWidget.doSizing(CalendarWidget.java:335)
    at com.bradrydzewski.gwt.calendar.client.CalendarWidget.refresh(CalendarWidget.java:327)
    at com.bradrydzewski.gwt.calendar.client.CalendarWidget.setView(CalendarWidget.java:128)
    at com.bradrydzewski.gwt.calendar.client.Calendar.setView(Calendar.java:95)
    at com.qwest.sa.ncms.client.presenter.CalendarPresenter$7.onDateRequested(CalendarPresenter.java:144)
    at com.bradrydzewski.gwt.calendar.client.event.DateRequestEvent.dispatch(DateRequestEvent.java:101)
    at com.bradrydzewski.gwt.calendar.client.event.DateRequestEvent.dispatch(DateRequestEvent.java:1)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.fireEvent(HandlerManager.java:65)
    at com.google.gwt.event.shared.HandlerManager$HandlerRegistry.access$1(HandlerManager.java:53)
    at com.google.gwt.event.shared.HandlerManager.fireEvent(HandlerManager.java:178)
    at com.google.gwt.user.client.ui.Widget.fireEvent(Widget.java:52)
    at com.bradrydzewski.gwt.calendar.client.event.DateRequestEvent.fire(DateRequestEvent.java:48)
    at com.bradrydzewski.gwt.calendar.client.CalendarWidget.fireDateRequestEvent(CalendarWidget.java:461)
    at com.bradrydzewski.gwt.calendar.client.monthview.MonthView.onSingleClick(MonthView.java:414)
    at com.bradrydzewski.gwt.calendar.client.CalendarWidget.onMouseDown(CalendarWidget.java:419)
    at com.bradrydzewski.gwt.calendar.client.InteractiveWidget.onBrowserEvent(InteractiveWidget.java:177)
    at com.google.gwt.user.client.DOM.dispatchEventImpl(DOM.java:1307)
    at com.google.gwt.user.client.DOM.dispatchEvent(DOM.java:1263)
    at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessagesWhileWaitingForReturn(BrowserChannel.java:1713)
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:165)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:120)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:507)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:264)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:188)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.gwt.dev.shell.MethodAdaptor.invoke(MethodAdaptor.java:103)
    at com.google.gwt.dev.shell.MethodDispatch.invoke(MethodDispatch.java:71)
    at com.google.gwt.dev.shell.OophmSessionHandler.invoke(OophmSessionHandler.java:157)
    at com.google.gwt.dev.shell.BrowserChannel.reactToMessages(BrowserChannel.java:1668)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:401)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:222)
    at java.lang.Thread.run(Thread.java:619)

Use Case:


Assumptions:
1.
2.
3.

Exceptions:
1.
2.
3.

Code / psuedo-code:

```

Original issue reported on code.google.com by `murali...@gmail.com` on 23 Jul 2010 at 9:23

Attachments:
- [dayview.GIF](https://storage.googleapis.com/google-code-attachments/gwt-cal/issue-73/comment-0/dayview.GIF)

**Comment by GoogleCodeExporter** [comment]
Original comment by `Brad.Ryd...@gmail.com` on 15 Aug 2010 at 9:23
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
What is the status of this issue?
```

Original comment by `Andriy.K...@gmail.com` on 8 Jul 2011 at 9:35

**Comment by GoogleCodeExporter** [comment]
```
Is or will there be a fix for that issue?
```

Original comment by `nmoeller...@googlemail.com` on 21 Feb 2013 at 2:17

**Comment by GoogleCodeExporter** [comment]
```
The exception is now fixed in rev 445.

The proper solution needs a bit more work. I'm checking how is dealing with 
this case Google/iCal

Regards
```

Original comment by `ctasada` on 24 Feb 2013 at 2:23
- Changed state: **Started**
- Added labels: **Release0.9.5**

**Comment by GoogleCodeExporter** [comment]
```
The proper fix could be an scrollbar, but we need to define somewhere the 
maximum height

Another solution would be a collapse button.

Votes?
```

Original comment by `ctasada` on 24 Feb 2013 at 3:00

**Comment by GoogleCodeExporter** [comment]
```
+1 for the scrollbar solution with editable height value in calendar properties
```

Original comment by `nmoeller...@googlemail.com` on 26 Feb 2013 at 8:00

**Comment by GoogleCodeExporter** [comment]
```
Done in rev 446

The current behaviour is the default one. If the scrollbar is wanted then is 
only a matter of setting the maximum desired height in pixels using the next 
method from the CalendarSetting class: 
setMultiDayMaxPixelsHeight(heightInPixels)
```

Original comment by `ctasada` on 28 Feb 2013 at 9:13
- Changed state: **PendingReview**

**Comment by GoogleCodeExporter** [comment]
```
Thx in advance. I will try it out as soon as the new version is released.
```

Original comment by `nmoeller...@googlemail.com` on 4 Mar 2013 at 10:21

**Comment by GoogleCodeExporter** [comment]
```
If you can test it with the trunk code much better. Once the release is done it 
will be considered stable code and any change will be much difficult
```

Original comment by `ctasada` on 5 Mar 2013 at 9:11

**Comment by GoogleCodeExporter** [comment]
```
I understand. I will try to test it whithin the next days. Right now i am a 
little bit short in time. Thx for your effort.
```

Original comment by `nmoeller...@googlemail.com` on 7 Mar 2013 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
The new feature works as expected. Thx.

While testing i saw that my month view now starts on sunday not on monday 
anymore. And the layout of the monthview is messed up. Is that something you 
working at?
```

Original comment by `nmoeller...@googlemail.com` on 8 Mar 2013 at 11:51

**Comment by GoogleCodeExporter** [comment]
```
Not really. The day the week starts depends on a setting based in the Locale by 
default. 

If you feel it's a bug, please open an issue with an screenshot and as much 
information as possible to reproduce and fix it.

Thanks.
```

Original comment by `ctasada` on 8 Mar 2013 at 3:30

**Comment by GoogleCodeExporter** [comment]
```
All solved now.

I had to rename my CalendarConstants.properties to 
CalendarConstants_de.properties to be applied because the locale is set to 
"de". With the old version(9.3) it was not necessary because there was no 
default property file for locale "de".

The layout problem on the month view was within the css file from my custom 
theme. I had to do some updating because of the new css classes.

Thx for your help.

```

Original comment by `nmoeller...@googlemail.com` on 11 Mar 2013 at 9:22
